### ISSUE TITLE
Xerxes DOS

### ISSUE THREAD

**Issue by iloveboobs1** [zanyarjamal/xerxes#1]
I dont know what im doing wrong but this tool is not dosing shit website still up running

**Comment by d0geda** [comment]
Man you need to use more computers cuz they have good servers

**Comment by zanyarjamal** [comment]
it takes down websites with low bandwidth

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪

**Comment by username836** [comment]
Let's do it together 💪
