### ISSUE TITLE
bash: gcc: command not found

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [zanyarjamal/xerxes#3]
y when i try open the script i get **bash: gcc: command not found**

NOTE: i open from kali light + root acc
plz reply FASt

**Comment by leopoldobrines7** [comment]
Install gcc, prohacker!

**Comment by OBrien197** [comment]
Muy buen código C

**Comment by noscodes** [comment]
you cant install gcc with a light version, download a full version 2gb+ from kali website then do apt-get install gcc; only if gcc isnt already installed which you can test by doing "gcc"

**Comment by paradoxnafi** [comment]
`sudo apt install gcc make build-essential`
Now compile it by doing `make xerxes`

**Comment by Kanonahmed** [comment]
bash: gcc: command not found
--


on windows

**Comment by EsmailELBoBDev2** [comment]
OMG look at me there :joy: :joy:  whos imagine someone like me not know anything with linux to do projects like what i working on now, WOW & thx guys its been long time & thx owner for not closing my ticket, damn :joy: :joy:
